services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_THEBACKEND_API_BASE_URL: "https://thebackend.rocket-champ.pw"
    container_name: nextjs-web
    networks:
      - default
      - npm_default
    restart: always
    environment:
      - HOSTNAME=0.0.0.0

networks:
  npm_default:
    external: true
